### ISSUE TITLE
Generate a work report

### ISSUE THREAD

**Issue by Rahel-A** [unfog-io/unfog-cli#11]
Worktime displays time spent per tag. Would it be possible to generate a report based on a date range?

I want to look at how much time was spent per task for all tasks in the current week.

**Comment by soywod** [comment]
This feature was present in [Unfog predecessor](https://github.com/soywod/kronos.vim#worktime). I plan to re-implement it with very soon, [see this issue](https://github.com/unfog-io/unfog-cli/issues/9) for the progression.

**Comment by soywod** [comment]
The worktime date range has been introduced in the [last release](https://github.com/unfog-io/unfog-cli/releases/tag/v0.2.2). I would love to get your feedback :)

**Comment by soywod** [comment]
The worktime date range has been added in the [last release](https://github.com/unfog-io/unfog-cli/releases/tag/v0.2.2). I would love your feedback :)

**Comment by soywod** [comment]
Worktime date range and due time added in [v0.3.0](https://github.com/unfog-io/unfog-cli/releases/tag/v0.3.0) :tada:

**Comment by Rahel-A** [comment]
Side note: I'm running zsh, therefore I have to escape the brackets.

Thanks for the quick update, but this isn't exactly what I requested.

Right now I'd have to run  `unfog worktime +task1` and repeat for each task I've done in current week to determine time spent per task as there is no way for me to check the time spent on each tasks I've done in a week.
This just gives me an overview:
```unfog worktime \[060120 \]100120
unfog: wtime global

DATE       |WORKTIME
2020-01-06 |1 min 21s 672ms
TOTAL      |1 min 21s 672ms```

What I'd like is to be able to fill a workcard like this:
![image](https://user-images.githubusercontent.com/8069846/71816464-93152000-307a-11ea-87eb-4e8d9bfe033a.png)

So something like this would work for me:
```unfog worktime \[060120 \]100120
unfog: wtime global

ID | CONTEXT    | DATE            |WORKTIME
1  | task1 task2  | 2020-01-06 |1 min 21s 672ms
2  | task2            | 2020-01-06 |1 min 21s 672ms
TOTAL                                      |1 min 21s 672ms```

**Comment by soywod** [comment]
What I can do is to add a column `WORKTIME` at the end of the `list` table (after `DUE`)? This way you have access to the worktime per task.

**Comment by Rahel-A** [comment]
> What I can do is to add a column `WORKTIME` at the end of the `list` table (after `DUE`)? This way you have access to the worktime per task.

This is a good solution but list doesn't currently allow filtering with range. If you also add that then I'd satisfied.

**Comment by soywod** [comment]
Sounds good to me. Adding the `WORKTIME` column and the filtering system. I will let you know :)

**Comment by soywod** [comment]
I tried with zsh, I don't have the problem of `[`. It could be related to plugins?

**Comment by Rahel-A** [comment]
> I tried with zsh, I don't have the problem of `[`. It could be related to plugins?

Hmm, I think maybe oh-my-zsh enables [filename generation](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Filename-Generation)

**Comment by soywod** [comment]
I will keep `[` and `]` and wait for other feedbacks. About the worktime, I decided to change the `worktime` command itself. It looks like this:

![image](https://user-images.githubusercontent.com/10437171/72210877-2c509600-34c2-11ea-8052-37f684ba4e8e.png)

I will deploy the next release soon. Does it fit your needs?

**Comment by Rahel-A** [comment]
Yeah that works great!

**Comment by soywod** [comment]
This report is now accessible with the `--more` option. By default (without this option), it shows the compact version of worktime. See https://github.com/unfog-io/unfog-cli#more.
