### ISSUE TITLE
hyphens in tasks terminate input

### ISSUE THREAD

**Issue by norseghost** [unfog-io/unfog-cli#12]
I added a task containing an hyphen: `unfog create download author - title +admin`

This seemed to succeed; however, the resulting task was terminated just before the hyphen; and also lost the `+admin` context

this might be an input redirection issue?

(I tried this first in unfog-vim; which confused vim greatly)

**Comment by soywod** [comment]
It's a parsec problem, the word expression is not precise enough (indeed, everything starting by `+` or `-` is excluded): https://github.com/unfog-io/unfog-cli/blob/c65194b32bf42fd09d0c982d6f8a34bd107d76e8/src/Parsec.hs#L194-L199.
I will fix ASAP. Thank you for reporting the issue :)

**Comment by soywod** [comment]
Fixed in https://github.com/unfog-io/unfog-cli/compare/d2f4f..388ee. Set more precise selector (`sepBy` instead of `many`), and add test.
