### ISSUE TITLE
worktime seems to have debug information included in output

### ISSUE THREAD

**Issue by norseghost** [unfog-io/unfog-cli#15]
when I issue `unfog worktime`, the output includes

~~~
2019-12-28 04:44:22.300977301 UTC
Nothing
Nothing
[Task {_id <..snip..>
~~~

before the wtime table. This does not seem intentional.

**Comment by soywod** [comment]
Which version do you have? I think I left a `print` somewhere in a previous version, it should be fixed with the latest release.
