### ISSUE TITLE
allow selection of tags without prepending + [discussion]

### ISSUE THREAD

**Issue by norseghost** [unfog-io/unfog-cli#16]
The `+tag` syntax makes sense when defining a task; but it trips me up when switching  contexts etc.

Would it make sense to allow tags to be referenced without the `+`?

**Comment by soywod** [comment]
I have the same feeling. I wanted to be consistent, but it seems I'm not the only one who has trouble with. I will push sth soon. Thanks :)

**Comment by soywod** [comment]
I made the `+` optional for `context` and `worktime` commands. It will be available in the next release.
