### ISSUE TITLE
Mark done task as not done (undo)

### ISSUE THREAD

**Issue by dutchgecko** [unfog-io/unfog-cli#20]
Hi,

Would it be possible to include a method to mark a done tag as not done? Basically, some kind of undo command for if I accidentally mark a task as done.

It might be logical for the command to only be available while inside the 'done' context.

**Comment by soywod** [comment]
Command `undone` added in 8ce5ed909575230c17e0a1404bebf6cf051408a7. It will be present in the next release. Thanks for the good idea :)

**Comment by soywod** [comment]
Feature added in [v0.4.0](https://github.com/unfog-io/unfog-cli/releases/tag/v0.4.0) :tada:
