### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by mohsen-mohammadi** [unfog-io/unfog-cli#26]
Thanks for creating this excellent software.
I've created an [AUR package for unfog-cli](https://aur.archlinux.org/packages/unfog-cli-bin) and think it might be a good idea to mention it in the README.
Assuming your Arch readers have the commonly used `yay` installed, `yay -S unfog-cli-bin` could be used to install unfog from AUR.

**Comment by soywod** [comment]
Thank you so much @mohsen-mohammadi! I'm a Arch user also and it's a very good idea. Would you like to update the README also (the install section)?

**Comment by mohsen-mohammadi** [comment]
Thanks for including it in the REAME.
Yes, you're right about the upstream URL. I fixed it.

**Comment by soywod** [comment]
@mohsen-mohammadi the link seems not up-to-date anymore, since I removed unfog from its organization. Could you update it?
