### ISSUE TITLE
install.sh not working with Dash

### ISSUE THREAD

**Issue by Bherzet** [unfog-io/unfog-cli#28]
Shebang in `install.sh` refers to `/bin/sh`. On Debian 10 and Ubuntu 18.04 (and I guess most Linux distributions, really), this points to Dash:

```
$ ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Jan 17  2019 /bin/sh -> dash
```
The problem is that Dash (version `0.5.10.2-5`) doesn't support the syntax used in the script and produces multiple errors upon running, such as:

```
./ins.sh: 4: [: unexpected operator
```
Running the installation script with Bash works just fine, so the easy solution is to replace `sh` with `bash` (both in the code and the `curl [...] | sh` command in the documentation). The other solution would be to rewrite the script so it actually works with Dash.

**Comment by soywod** [comment]
Thank you to have point it out (and for the PR). It will be present in the next release!
