### ISSUE TITLE
[~]/.config/unfog/store: openFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by dutchgecko** [unfog-io/unfog-cli#5]
After a fresh installation from git, running `unfog create projectname +some +tags` I get the error in the title. The `~/.config/unfog` directory does indeed not exist, and should probably be made by the app. Manually creating the directory allows the command to succeed.

edit: checked out revision is 005380bd7f1e4e97fb382a17fad3253f1b7ec47b

**Comment by soywod** [comment]
Indeed, the folder should be created automatically if it does not exist. I'll fix ASAP.

**Comment by soywod** [comment]
Fixed with cf3c6cf6f7c28b6382f6c30abfd9db6763f3fd4c, it will be included in the next release.
