### ISSUE TITLE
installer script does not work

### ISSUE THREAD

**Issue by norseghost** [unfog-io/unfog-cli#7]
I suspect some sort of curl (maybe HTTP redirect) issue.
I have not been able to get curl to be more useful in debugging (yet).

however, I am able to download without issue if I extract the curl command from `install.sh` **if** I remove the `-s` flag. With it present, I get a zero-length file.

This does not work in `install.sh` itself, weirdly.

bash/arch FWIW

**Comment by soywod** [comment]
I found the problem. It's because I tagged my release as `pre-release`, since we are not in a `v1`, but it prevents the script to find the latest binary. After tagging it as `release`, the script worked as expected. Can you confirm from your side?

**Comment by norseghost** [comment]
yup, that did it!
